# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI/CD flow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      #Step-1
    - name: Checkout
      uses: actions/checkout@v3
      with:
        - fetch-depth: 0 # required for github-action-get-previous-tag

      #Step-2
    - name: Cache jdk binary
      uses: actions/cache@v2
      with:
        path: ${{ runner.temp }}/jdk
        key: ${{ runner.os }}-jdk-17
        restore-keys: ${{ runner.os }}-jdk

      #Step-3
    - name: retrieve latest corretto 17 jdk
      run: |
        test -d ${{ runner.temp }}/jdk || mkdir ${{ runner.temp }}/jdk
        test -f ${{ runner.temp }}/jdk/amazon-corretto-17-x64-linux-jdk.tar.gz || ( wget -qP ${{ runner.temp }}/jdk https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz )

      #Step-4
    - name: Set up JDK 17 from file
      uses: actions/setup-java@v2
      with:
        distribution: 'jdkfile'
        jdkFile: ${{ runner.temp }}/jdk/amazon-corretto-17-x64-linux-jdk.tar.gz
        java-version: '17.0.0'
        architecture: x64
        cache: "maven"

      #Step-5
    - name: Build with Maven
      run: mvn clean install

      #Step-6
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: srivatsam6/springboot-images
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      #Step-7
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

      #Step-8
    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}

      #Step-9
    - name: Build, tag, and push docker image to Amazon ECR Public
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: e0c7z5m9
        REPOSITORY: github-actions
        IMAGE_TAG: ${{ steps.semvers.outputs.patch }}
      run: |
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG

      #Step-10
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      #Step-11
    - name: Build Tag and push Docker Image
      env:
        IMAGE_NAME: srigithubactions.jfrog.io/sri-docker/jfrog-docker-example-image:${{ steps.semvers.outputs.patch }}
      run: |
        jf docker build -t $IMAGE_NAME .
        jf docker push $IMAGE_NAME

      #Step-12
    - name: Publish Build info With JFrog CLI
      env:
        # Generated and maintained by GitHub
        JFROG_CLI_BUILD_NAME: jfrog-docker-build-example
        # JFrog organization secret
        JFROG_CLI_BUILD_NUMBER: ${{ steps.semvers.outputs.patch }}
      run: |
        # Export the build name and build number
        # Collect environment variables for the build
        jf rt build-collect-env
        # Collect VCS details from git and add them to the build
        jf rt build-add-git
        # Publish build info
        jf rt build-publish

      #Step-13
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
